// ------------------------------------------------------------------------------
//  <auto-generated>
//      此代码由编码的 UI 测试生成器生成。
//      版本: 15.0.0.0
//
//      如果重新生成代码，则更改此文件可能会导致错误的行为，
//      并将丢失这些更改。
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Learn.CodeUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("编码的 UI 测试生成器", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uIGoogleChrome1个运行窗口Button = this.UI运行中的应用程序Window.UI运行中的应用程序ToolBar.UIGoogleChrome1个运行窗口Button;
            #endregion

            // 右-单击 “Google Chrome - 1 个运行窗口” 按钮
            Mouse.Click(uIGoogleChrome1个运行窗口Button, MouseButtons.Right, ModifierKeys.None, new Point(13, 10));
        }
        
        #region Properties
        public UI运行中的应用程序Window UI运行中的应用程序Window
        {
            get
            {
                if ((this.mUI运行中的应用程序Window == null))
                {
                    this.mUI运行中的应用程序Window = new UI运行中的应用程序Window();
                }
                return this.mUI运行中的应用程序Window;
            }
        }
        #endregion
        
        #region Fields
        private UI运行中的应用程序Window mUI运行中的应用程序Window;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "15.0.26208.0")]
    public class UI运行中的应用程序Window : WinWindow
    {
        
        public UI运行中的应用程序Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "运行中的应用程序";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSTaskSwWClass";
            this.WindowTitles.Add("运行中的应用程序");
            #endregion
        }
        
        #region Properties
        public UI运行中的应用程序ToolBar UI运行中的应用程序ToolBar
        {
            get
            {
                if ((this.mUI运行中的应用程序ToolBar == null))
                {
                    this.mUI运行中的应用程序ToolBar = new UI运行中的应用程序ToolBar(this);
                }
                return this.mUI运行中的应用程序ToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UI运行中的应用程序ToolBar mUI运行中的应用程序ToolBar;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "15.0.26208.0")]
    public class UI运行中的应用程序ToolBar : WinToolBar
    {
        
        public UI运行中的应用程序ToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "运行中的应用程序";
            this.WindowTitles.Add("运行中的应用程序");
            #endregion
        }
        
        #region Properties
        public WinButton UIGoogleChrome1个运行窗口Button
        {
            get
            {
                if ((this.mUIGoogleChrome1个运行窗口Button == null))
                {
                    this.mUIGoogleChrome1个运行窗口Button = new WinButton(this);
                    #region 搜索条件
                    this.mUIGoogleChrome1个运行窗口Button.SearchProperties[WinButton.PropertyNames.Name] = "Google Chrome - 1 个运行窗口";
                    this.mUIGoogleChrome1个运行窗口Button.WindowTitles.Add("运行中的应用程序");
                    #endregion
                }
                return this.mUIGoogleChrome1个运行窗口Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIGoogleChrome1个运行窗口Button;
        #endregion
    }
}
